Repository Backbase/golden-sample-app, pull requests merged in 2023-03, with the labels that each got.

#132 add: user credentials to login
  README.md
Labels: enhancement

#131 fix: 404 issue with the aggregation balance endpoint
  libs/transfer/src/lib/components/make-transfer-form/make-transfer-form.component.html
  libs/transfer/src/lib/components/make-transfer-form/make-transfer-form.component.ts
  libs/transfer/src/lib/services/make-transfer-accounts.http.service.spec.ts
  libs/transfer/src/lib/services/make-transfer-accounts.http.service.ts
  libs/transfer/src/lib/state/make-transfer-journey-state.service.spec.ts
  libs/transfer/src/lib/state/make-transfer-journey-state.service.ts
  libs/transfer/src/lib/views/make-transfer-summary-view/make-transfer-summary-view.component.spec.ts
  libs/transfer/src/lib/views/make-transfer-view/make-transfer-view.component.html
  libs/transfer/src/lib/views/make-transfer-view/make-transfer-view.component.ts
  package-lock.json
Labels: bug, enhancement

#133 WF-687: App size optimization
  .github/workflows/pull-request.yml
  Dockerfile
  apps/golden-sample-app/src/app/app-routing.module.ts
  apps/golden-sample-app/src/app/app.module.ts
  apps/golden-sample-app/src/app/custom-payment/components/initiator/initiator.component.ts
  apps/golden-sample-app/src/app/custom-payment/components/initiator/initiator.service.spec.ts
  apps/golden-sample-app/src/app/locale-selector/locales.service.ts
  apps/golden-sample-app/src/app/positive-pay/positive-pay-journey-bundle.module.ts
  apps/golden-sample-app/src/app/services/journey-communication.service.ts
  libs/ach-positive-pay/src/lib/models/accounts.ts
  libs/ach-positive-pay/src/lib/services/ach-positive-pay.http.service.ts
  libs/ach-positive-pay/src/lib/views/ach-positive-pay-new-rule/ach-positive-pay-new-rule.component.spec.ts
  libs/ach-positive-pay/src/lib/views/ach-positive-pay-new-rule/ach-positive-pay-new-rule.component.ts
  libs/ach-positive-pay/src/lib/views/ach-positive-pay-new-rule/ach-positive-pay-rule-form/ach-positive-pay-rule-form.component.ts
  libs/transactions/src/lib/communication/index.ts
  libs/transactions/src/lib/components/transaction-item/transaction-item.component.ts
  libs/transactions/src/lib/extensions/transaction-addition-details.ts
  libs/transactions/src/lib/mocks/transactions-mocks.ts
  libs/transactions/src/lib/pipes/filter-transactions.pipe.ts
  libs/transactions/src/lib/services/arrangements.service.spec.ts
  libs/transactions/src/lib/services/arrangements.service.ts
  libs/transactions/src/lib/services/transactions.http.service.spec.ts
  libs/transactions/src/lib/services/transactions.http.service.ts
  libs/transactions/src/lib/views/transaction-details-view/transaction-details-view.component.ts
  libs/transactions/src/lib/views/transactions-view/transactions-view.component.spec.ts
  libs/transfer/src/lib/services/make-transfer-accounts.http.service.ts
  package-lock.json
  package.json
Labels: bug
